/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portlet.documentlibrary.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.document.library.kernel.model.DLEncryption;
import com.liferay.document.library.kernel.model.DLEncryptionModel;
import com.liferay.document.library.kernel.model.DLEncryptionSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the DLEncryption service. Represents a row in the &quot;DLEncryption&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link DLEncryptionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DLEncryptionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DLEncryptionImpl
 * @see DLEncryption
 * @see DLEncryptionModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class DLEncryptionModelImpl extends BaseModelImpl<DLEncryption>
	implements DLEncryptionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a document library encryption model instance should use the {@link DLEncryption} interface instead.
	 */
	public static final String TABLE_NAME = "DLEncryption";
	public static final Object[][] TABLE_COLUMNS = {
			{ "fileEncryptionId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "fileEntryId", Types.BIGINT },
			{ "fileVersionId", Types.BIGINT },
			{ "status", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("fileEncryptionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fileEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fileVersionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table DLEncryption (fileEncryptionId LONG not null primary key,groupId LONG,fileEntryId LONG,fileVersionId LONG,status VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table DLEncryption";
	public static final String ORDER_BY_JPQL = " ORDER BY dlEncryption.fileEncryptionId DESC";
	public static final String ORDER_BY_SQL = " ORDER BY DLEncryption.fileEncryptionId DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.portal.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.liferay.document.library.kernel.model.DLEncryption"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.portal.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.liferay.document.library.kernel.model.DLEncryption"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.portal.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.com.liferay.document.library.kernel.model.DLEncryption"),
			true);
	public static final long FILEENTRYID_COLUMN_BITMASK = 1L;
	public static final long FILEVERSIONID_COLUMN_BITMASK = 2L;
	public static final long FILEENCRYPTIONID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static DLEncryption toModel(DLEncryptionSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		DLEncryption model = new DLEncryptionImpl();

		model.setFileEncryptionId(soapModel.getFileEncryptionId());
		model.setGroupId(soapModel.getGroupId());
		model.setFileEntryId(soapModel.getFileEntryId());
		model.setFileVersionId(soapModel.getFileVersionId());
		model.setStatus(soapModel.getStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<DLEncryption> toModels(DLEncryptionSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<DLEncryption> models = new ArrayList<DLEncryption>(soapModels.length);

		for (DLEncryptionSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.portal.util.PropsUtil.get(
				"lock.expiration.time.com.liferay.document.library.kernel.model.DLEncryption"));

	public DLEncryptionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _fileEncryptionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFileEncryptionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _fileEncryptionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DLEncryption.class;
	}

	@Override
	public String getModelClassName() {
		return DLEncryption.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("fileEncryptionId", getFileEncryptionId());
		attributes.put("groupId", getGroupId());
		attributes.put("fileEntryId", getFileEntryId());
		attributes.put("fileVersionId", getFileVersionId());
		attributes.put("status", getStatus());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long fileEncryptionId = (Long)attributes.get("fileEncryptionId");

		if (fileEncryptionId != null) {
			setFileEncryptionId(fileEncryptionId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long fileEntryId = (Long)attributes.get("fileEntryId");

		if (fileEntryId != null) {
			setFileEntryId(fileEntryId);
		}

		Long fileVersionId = (Long)attributes.get("fileVersionId");

		if (fileVersionId != null) {
			setFileVersionId(fileVersionId);
		}

		String status = (String)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}
	}

	@JSON
	@Override
	public long getFileEncryptionId() {
		return _fileEncryptionId;
	}

	@Override
	public void setFileEncryptionId(long fileEncryptionId) {
		_columnBitmask = -1L;

		_fileEncryptionId = fileEncryptionId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getFileEntryId() {
		return _fileEntryId;
	}

	@Override
	public void setFileEntryId(long fileEntryId) {
		_columnBitmask |= FILEENTRYID_COLUMN_BITMASK;

		if (!_setOriginalFileEntryId) {
			_setOriginalFileEntryId = true;

			_originalFileEntryId = _fileEntryId;
		}

		_fileEntryId = fileEntryId;
	}

	public long getOriginalFileEntryId() {
		return _originalFileEntryId;
	}

	@JSON
	@Override
	public long getFileVersionId() {
		return _fileVersionId;
	}

	@Override
	public void setFileVersionId(long fileVersionId) {
		_columnBitmask |= FILEVERSIONID_COLUMN_BITMASK;

		if (!_setOriginalFileVersionId) {
			_setOriginalFileVersionId = true;

			_originalFileVersionId = _fileVersionId;
		}

		_fileVersionId = fileVersionId;
	}

	public long getOriginalFileVersionId() {
		return _originalFileVersionId;
	}

	@JSON
	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		_status = status;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			DLEncryption.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DLEncryption toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (DLEncryption)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DLEncryptionImpl dlEncryptionImpl = new DLEncryptionImpl();

		dlEncryptionImpl.setFileEncryptionId(getFileEncryptionId());
		dlEncryptionImpl.setGroupId(getGroupId());
		dlEncryptionImpl.setFileEntryId(getFileEntryId());
		dlEncryptionImpl.setFileVersionId(getFileVersionId());
		dlEncryptionImpl.setStatus(getStatus());

		dlEncryptionImpl.resetOriginalValues();

		return dlEncryptionImpl;
	}

	@Override
	public int compareTo(DLEncryption dlEncryption) {
		int value = 0;

		if (getFileEncryptionId() < dlEncryption.getFileEncryptionId()) {
			value = -1;
		}
		else if (getFileEncryptionId() > dlEncryption.getFileEncryptionId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DLEncryption)) {
			return false;
		}

		DLEncryption dlEncryption = (DLEncryption)obj;

		long primaryKey = dlEncryption.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		DLEncryptionModelImpl dlEncryptionModelImpl = this;

		dlEncryptionModelImpl._originalFileEntryId = dlEncryptionModelImpl._fileEntryId;

		dlEncryptionModelImpl._setOriginalFileEntryId = false;

		dlEncryptionModelImpl._originalFileVersionId = dlEncryptionModelImpl._fileVersionId;

		dlEncryptionModelImpl._setOriginalFileVersionId = false;

		dlEncryptionModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<DLEncryption> toCacheModel() {
		DLEncryptionCacheModel dlEncryptionCacheModel = new DLEncryptionCacheModel();

		dlEncryptionCacheModel.fileEncryptionId = getFileEncryptionId();

		dlEncryptionCacheModel.groupId = getGroupId();

		dlEncryptionCacheModel.fileEntryId = getFileEntryId();

		dlEncryptionCacheModel.fileVersionId = getFileVersionId();

		dlEncryptionCacheModel.status = getStatus();

		String status = dlEncryptionCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			dlEncryptionCacheModel.status = null;
		}

		return dlEncryptionCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{fileEncryptionId=");
		sb.append(getFileEncryptionId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", fileEntryId=");
		sb.append(getFileEntryId());
		sb.append(", fileVersionId=");
		sb.append(getFileVersionId());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.liferay.document.library.kernel.model.DLEncryption");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>fileEncryptionId</column-name><column-value><![CDATA[");
		sb.append(getFileEncryptionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fileEntryId</column-name><column-value><![CDATA[");
		sb.append(getFileEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fileVersionId</column-name><column-value><![CDATA[");
		sb.append(getFileVersionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = DLEncryption.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			DLEncryption.class, ModelWrapper.class
		};
	private long _fileEncryptionId;
	private long _groupId;
	private long _fileEntryId;
	private long _originalFileEntryId;
	private boolean _setOriginalFileEntryId;
	private long _fileVersionId;
	private long _originalFileVersionId;
	private boolean _setOriginalFileVersionId;
	private String _status;
	private long _columnBitmask;
	private DLEncryption _escapedModel;
}